inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false

# These `.to_time` conversions were obviously done for a reason back
# in the day. I'm not confident enough in RuboCop's autocorrections
# to change the behaviour by removing them in files like
# `app/presenters/guide_presenter.rb`.
Rails/Date:
  Enabled: false
